### ISSUE TITLE
ACF Block: Content Image Overlap

### ISSUE THREAD

**Issue by wmcconnell** [asu-ke-web-services/UDS-WordPress-Theme#100]
We need to create a block to implement the 'content image overlap' layout [shown here in the XD file](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/674ebe9d-bcfd-48c9-a3eb-37efe95f4f4a/).

The XD file says that any type of content could go inside that white area, but we may want to concentrate first on building one that mimics this exact setup - as it will likely be the most common. If we do that, we should allow the user to:

- choose the background image
- enter a headline
- enter a sub-heading
- enter the body text
- choose which orientation (picture on the right or the left)

If you're feeling fancier, you could try the `<InnerBlocks />` technique, but we may want to limit the inner blocks to simple things like headings and text. I don't think we want to put any images inside that white area, for example.

**Comment by SteveRyan-ASU** [comment]
Grabbing this one - I've got a head start on way to lay this out using CSS grid. The effect is to make it scale to the width of a normal bootstrap column. Variants for text-left and text-right will be included.

**Comment by SteveRyan-ASU** [comment]
Closed by #118
