### ISSUE TITLE
ACF Block: Card and Image

### ISSUE THREAD

**Issue by wmcconnell** [asu-ke-web-services/UDS-WordPress-Theme#101]
We need to create a block to implement the "card and image" content structure [shown here in the XD file](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/674ebe9d-bcfd-48c9-a3eb-37efe95f4f4a/). There isn't much to go on, in terms of specific layout, as nobody has tried to implement this one yet, but the user should be able to do the following:

- configure the card (it should be an embedded card block)
- choose the image
- choose to put the card on the left or the right

**Comment by zainabD** [comment]
I think this can be done using Steve's work in the background section block [UDS Background Section #132 ].
