### ISSUE TITLE
ACF Block: Quote on Image Background

### ISSUE THREAD

**Issue by wmcconnell** [asu-ke-web-services/UDS-WordPress-Theme#102]
We need to create a block to implement the 'quote on image background' content structure [shown here in the XD file](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/674ebe9d-bcfd-48c9-a3eb-37efe95f4f4a/). The user should be able to:

- choose the image
- choose the color of the large quotes
- enter the quote text
- enter the person's name
- enter an optional description, shown below the name

**Comment by zainabD** [comment]
I think this can be done using Steve's work in the background section block [UDS Background Section #132 ], please check this solution and see if we still need to build this block separately.

**Comment by zainabD** [comment]
Closing this issue for now, we will try to build a more generic block to obtain this background feature.
