### ISSUE TITLE
Question: List Styling

### ISSUE THREAD

**Issue by wmcconnell** [asu-ke-web-services/UDS-WordPress-Theme#106]
Do we want to create any theme-specific styles to create lists the way we want them? We've discussed this already, but I'm creating this issue to remind us to settle on an answer and implement a solution.

**Comment by zainabD** [comment]
This was taken care of in the cor/list PR core/list block #158

**Comment by wmcconnell** [comment]
Closing this one out, per Zainab's comment above.
