### ISSUE TITLE
Add Alt attr to all images in ACF's blocks

### ISSUE THREAD

**Issue by zainabD** [asu-ke-web-services/UDS-WordPress-Theme#162]

**Comment by SteveRyan-ASU** [comment]
Conducted a quick audit of the field groups of the ACF blocks that are currently in the theme (as of 0.17). This may be an incomplete list, but good places to start looking would be:

- Blockquote. The "with image" presentation should include the ALT text on the included image.
- Card. The image at the top of the card may also need alt text applied.

Both of these watchpoints were discovered just by looking for Image fields within ACF that happened to be assigned the "image URL" return data point.
