### ISSUE TITLE
Fix Back-to-Top page button - incorrect scripting behavior

### ISSUE THREAD

**Issue by nathan-rollins** [asu-ke-web-services/UDS-WordPress-Theme#197]
FYI, we are not using the approved script for the Back-to-Top button provided in the UDS Bootstrap theme. Our button has missing logic in the script: the button should only appear after the user has scrolled past a specific range of the document AND they begin scrolling back up toward the top.

**Comment by zainabD** [comment]
This was fixed in this PR: Back to top function #205
