### ISSUE TITLE
Automatic featured image function produces PHP notices if Yoast SEO isn't present within the install

### ISSUE THREAD

**Issue by SteveRyan-ASU** [asu-ke-web-services/UDS-WordPress-Theme#214]
## Issue is about..
  - [x] a Bug Report

When the Yoast SEO plugin is not present within a WordPress install, the following PHP notices are produced within the admin.
```
Undefined variable: wpseo_primary_term at wp-content/themes/UDS-WordPress-Theme/inc/template-tags.php:175
Trying to access array offset on value of type null  at wp-content/themes/UDS-WordPress-Theme/inc/template-tags.php:217
```

Also: there is now a dedicated function within the Yoast SEO plugin to check and retrieve the term marked as "primary." See the following Stack Exchange answer for context: https://stackoverflow.com/a/63072165/3431495

A fix for this should probably check for the existence of `yoast_get_primary_term_id()`, then if present, just call it directly to retrieve the term ID for the taxonomy that you are investigating. (Category, here.). From there, the ACF call to the page hero background image should still be possible as a "backup" featured image. 

In the event that Yoast SEO isn't being used, the right logic to follow would be to loop through ANY assigned category at that point for the existence of a hero image.

**Comment by wmcconnell** [comment]
This was fixed with the merging of Steve's PR on featured images. Closing.
