### ISSUE TITLE
ACF: Revisit our decision to include ACF within the theme

### ISSUE THREAD

**Issue by SteveRyan-ASU** [asu-ke-web-services/UDS-WordPress-Theme#31]
The decision to include the free version of ACF wiithin our theme was made in order to take advantage of the plugin's capabilities (as developers) while not requiring additional actions for our users. 

That decision should be revisited in light of two important conversations that happened during our last UDS-WordPress project meeting:

- Including the plugin files within the theme requires the development team to manually update the plugin whenever an update is issued from the ACF team
- In order to take advantage of ACF Pro, the original bundled theme files need to be first "unplugged" from the theme.

**Comment by SteveRyan-ASU** [comment]
Offline @nathan-rollins and I chatted and figured out that the progression forward here would involve testing and discovery of a couple of additional items.

1. We would want to know whether or not the bundled ACF JSON files would still work if ACF was no longer directly included with the theme. 
2. We would want to understand how to best go about recommending (or even requiring) our end users to install at least the free version of ACF from the normal WordPress repository.

**Comment by SteveRyan-ASU** [comment]
Testing the first bullet point above. Commenting out the following line in `functions.php` effectively prevents the theme from loading the included version. https://github.com/asu-ke-web-services/UDS-WordPress-Theme/blob/bd28bd3b84bf5256fa64899c292eeba0f1418213/functions.php#L27

Then, when installing the ACF plugin from the repo and looking at the admin menu, I verified that the JSON files for our created ACF fields were present and waiting to be synced from the DB. The same is also true when activating the ACF Pro version of the plugin.

The UI for ACF also provided a clue that the plugin (out of the box) knew to look for config files in the `/acf-json` subfolder of the theme.

![image](https://user-images.githubusercontent.com/2085753/97761062-f799e380-1ac1-11eb-9c7d-214749b1ef9a.png)

**Comment by SteveRyan-ASU** [comment]
For the second bullet point above, I called upon my mental Rolodex of WordPress utility widgets. I remembered hearing about a PHP library for WordPress that provides a mechanism for recommending or installing other complementary plugins & themes. It was this one:

- https://github.com/TGMPA/TGM-Plugin-Activation
- https://tgmpluginactivation.com/

This library is well documented. It makes the claim that this is the recommended way that products sold within Code Canyon as well as distributed via WordPress.org should recommend other things to be installed. The idea here would be to configure this library to work with our theme, and then, upon initial activation:

- recommend or require ACF from the WordPress.org repo.
- recommend ACF Pro as an alternative to the free version.

**Comment by wmcconnell** [comment]
I was just going to suggest we do that on our own, via things like [get_plugins()](https://developer.wordpress.org/reference/functions/get_plugins/), but if it's been solved already we should use that solution.

**Comment by SteveRyan-ASU** [comment]
Closing this issue - we're committed to at least using ACF non-pro as a required utility for our theme, and TGMPA  has been implemented to make sure that the plugin is installed upon theme activation.
