### ISSUE TITLE
Custom Text Highlighting

### ISSUE THREAD

**Issue by wmcconnell** [asu-ke-web-services/UDS-WordPress-Theme#53]
We need the ability to add web standards highlighting (gold, black, etc.) to headings on our pages.

**Comment by SteveRyan-ASU** [comment]
Leaving some notes for myself. Looks like this will be accomplished by extending the native header block with the Format API to add a highlight button (or buttons) to the native block toolbar. When finished that button should apply a `<span></span` to highlighted text with the correct class. 

Start here: https://developer.wordpress.org/block-editor/tutorials/format-api/
Also: https://jeffreycarandang.com/how-to-create-custom-text-formats-for-gutenberg-block-editor/

**Comment by zainabD** [comment]
We added this feature to ACF heading.

**Comment by SteveRyan-ASU** [comment]
Going to reopen this although it might remain at the bottom of the to-do pile right now. The key difference between this task and the creation of the UDS-Header block using ACF is the ability to highlight only part of a header tag if that is desired.

Currently, the only output of the UDS-Header block looks like this:
```
<h2><span class="highlight-gold">Here is your fantastic headline.</span></h2>
```

But if we can modify the native header block using the technique noted above (`registerFormatType`), we can produce strings that look like: 
```
<h2>Here is your <span class="highlight-gold">fantastic</span> headline</h2>
```

... and potentially eliminate the UDS header block completely (eventually).
