### ISSUE TITLE
Documentation - Document Zainab's new Sidebars functionality

### ISSUE THREAD

**Issue by nathan-rollins** [asu-ke-web-services/UDS-WordPress-Theme#57]
I just realized I goofed after merging in Zainab's PR #25 that added her new sidebars feature. I forgot to have her document this feature in the README. 

I am assigning this issue to Zainab, and I ask that she write up proper documentation including screenshots that explains how sidebars now work.

**Comment by SteveRyan-ASU** [comment]
Closing this issue. Zainab's work on customizing the sidebar layout and functionality was overwritten by #72. Therefore no documentation is required here.
