### ISSUE TITLE
Bug: When activating theme first time, default values in the Customizer are ignored

### ISSUE THREAD

**Issue by nathan-rollins** [asu-ke-web-services/UDS-WordPress-Theme#60]
## Issue is about..
  - [X] a Bug Report

---

# Issue Overview for Bug Reports

## Steps to reproduce?

On a new website, install and activate the UDS WordPress Theme.

Some default settings are not being used:

1. The navigation menu should be Enabled by default. To enable the menu, the Customizer setting ("ASU Global Header") must be toggled to Disabled, then back to Enabled.
2. The website Endorsed Logos Preset (in "Site Settings") should default to the ASU logo. Instead, it defaults to nothing.

## Screenshots / Video
Current behavior: 
<img width="993" alt="Current default logo selector behavior" src="https://user-images.githubusercontent.com/1801352/99015513-6b9ca880-2512-11eb-86db-b8f720f557a3.png">

Intended behavior:
<img width="1013" alt="Desired default logo selector behavior" src="https://user-images.githubusercontent.com/1801352/99015544-79eac480-2512-11eb-9c57-ad1e35d761eb.png">

# Todos

 * Documentation

**Comment by zainabD** [comment]
This was solved by Walt. [Fix Default Values and Modernize the Customizer #78]
