### ISSUE TITLE
Bug: Image asset path in compiled SASS still references old theme name

### ISSUE THREAD

**Issue by SteveRyan-ASU** [asu-ke-web-services/UDS-WordPress-Theme#61]
The utility classes for any of the background textures that ship with UDS Boostrap 4 aren't working out of the box.

## Steps to reproduce?

1. Install a new copy of the theme in a new environment.
1. Create a `<div class="container-fluid bg network-white" style="height:20rem;"></div>` someplace on a blank page.
1. The background image should NOT show up, and should reference the old theme name in the `background-image` attribute for the div.

The cause for this error was a change in the variable that controls the default location of those image assets without also running a `gulp watch` or other SASS compiling method once the variable had been changed. Recompiling the SASS with the variable's default value resolved the problem.

**Comment by wmcconnell** [comment]
I forgot to bring this up in the meeting! Noticed this the other day on my local copy of the reference site - the 'Dividers' page was not showing any of the background images. Thanks, Steve!

**Comment by SteveRyan-ASU** [comment]
Adding a note: Pull request #72 will eventually close this issue. It added some styling for the default template, which triggered the SASS compiler as a result of the edits.
