### ISSUE TITLE
Menu Errors With Anything Below Grandchild Level

### ISSUE THREAD

**Issue by wmcconnell** [asu-ke-web-services/UDS-WordPress-Theme#70]
Creating a standard WordPress menu with items below the grandchild (third) level of nesting results in multiple 'Undefined index' errors on the menu if you have debug turned on. In cases where debug is off, there are no errors, obviously, but menu items below the grandchild level do go missing.

There are a couple of things to keep in mind here:

1) I don't think the standard, as it exists now, even allows for items below the grandchild level; I don't think the code we originally wrote even looks for them. The missing items are somewhat expected behavior, then.

2) Nothing stops a user, however, from using deeper nesting in the default WordPress menu builder.

3) The solution to this may be code, but might also touch on user permissions and how much we expect even our most hands-on clients to be able to modify main navigation menus.

**Comment by wmcconnell** [comment]
<img width="1307" alt="Screen Shot 2020-11-25 at 10 20 56 AM" src="https://user-images.githubusercontent.com/31013359/100261451-fa90c400-2f07-11eb-8050-51ea31162e3d.png">

**Comment by nathan-rollins** [comment]
Good call. You're right, Web Standards 2.0 doesn't allow for deeper menu levels. But we need to come up with a solution to prevent these errors. At a minimum we want:

1. Safety logic that ignores or trims menu arrays deeper than the Max 3 Levels permitted. At least prevent any errors from being triggered.
2. Document clearly how the Menu Builder works and clearly highlight that 3 levels is the maximum permitted.

A nice-to-have would be to display some error alert on the dashboard when the menus are invalid: e.g. "Error: Menus are only allowed to have a maximum of three levels. Any invalid menu entries will be ignored."

**Comment by wmcconnell** [comment]
I pushed a branch that addresses these items. It includes:

- A conditional wrapper around the code that was causing the errors
- All new comments throughout the file that I was using to better understand what was happening
- New CSS styles to highlight menu items that are four (or more) levels deep
- New context help on the Menu page explaining how the menu nesting works

It's late, so I'll add some documentation to the readme and start a PR in the morning.
