### ISSUE TITLE
Main Menu Not Displaying on Front End

### ISSUE THREAD

**Issue by danzo** [asu-ke-web-services/UDS-WordPress-Theme#71]
## Issue is about..
  - [ ] a Bug Report
  - [ ] I need help

## Please tell us about your environment:
  - **WordPress Version:** 5.5.3
  - **OS Version:** MacOS 10.14.6
  - **Browser:** Chrome (87.0.4280.67) | Firefox (83.0) | Safari(12.1.2) | iOS Safari(14)
  - **Node.js & NPM Versions:** Node.js 15.3.0 | NPM 6.14.9
  - **PHP Versions:** 7.3.9 (local server) | 7.4.12 (Pantheon)
---

# Issue Overview for Bugreports

No top main menu displaying on front end. I have this same issue on my local server and in a Pantheon sandbox. The Pantheon site is not a clone of the site on my local server. It is a new install via Pantheon's dashboard. Doesn't matter which menu (mine or example menus) I choose for that position, nothing shows. The menus do show in the footer position.

On mobile, the hamburger icon shows, but only the global header menu grid shows in the dropdown. The menu _does_ display correctly in the back end (Appearance > Customize). 

Both sites are bare installs of WP 5.5.3 with no plugins installed other than the required ACF. 

No browser extensions are enabled.

Debugging is enabled. No errors are showing on the front end or in the console.

## *Who* is the bug affecting?

Just me and my dev site.

## *When* does this occur?
Always

## *Where* on the platform does it happen?
Front end only

## *How* do we replicate the issue?
Install WP and ACF plugin. Install UDS-WordPress-Theme. Install Composer and Node modules. Run gulp watch. 

## Are there any related Issues and/or PRs?
Not that I'm aware of.

**Comment by danzo** [comment]
After many hours of frustration and submitting a bug report, of course I figured it out. 
Appearance > Customize > ASU Global Header is enabled by default. Disabling and re-enabling it has fixes the issue.

**Comment by nathan-rollins** [comment]
Sorry about that, Daniel. This is a known issue and in our queue to be fixed. 

Also, I want to share a quick heads-up that you are welcome to test our theme, but please keep in mind that it is very much work-in-progress and not ready for general use yet. Our web standards implementations up to this point has been focused on what we are most familiar with: pure HTML code in the Code Editor. 

We are now actively transitioning to Gutenberg Blocks and testing some different development strategies for implementing the ASU Web Standards 2.0 design features in a reusable blocks library. But we do not have any ready material to share with you yet or to put into in the theme framework itself. Once we have reached a Minimally Viable Product (MVP) that can allow us to build complete, baseline websites in Web Standards 2.0, we will make sure to pass word on to you and the rest of the ASU WordPress community.

Have a great holiday and thank you for submitting your notes!
