### ISSUE TITLE
.d-lg-none in nav menu set to display none above 992px width

### ISSUE THREAD

**Issue by newnamator** [asu-ke-web-services/UDS-WordPress-Theme#80]
## Issue is about..
  - [x] a Bug Report

## Please tell us about your environment:

  - **WordPress Version:** 5.5.1
  - **OS Version:** [Windows 10]
  - **Browser:** [ all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
  - **Language:** [S/CSS]

---

# Issue Overview for Bugreports

## Steps to reproduce?
Put the screen size into a responsive mode and for widths between 992 and 1260, the first child of the navigation menu has a class of d-lg-none, which is setting the initial nav item to a hidden state. 

## *Who* is the bug affecting?
This bug would affect everyone.

## *What* is affected by this bug?
In landscape tablets and small laptops, users would not be able to see the first nav child under the hamburger menu

## *Where* on the platform does it happen?
Chrome, FF and Edge

## Screenshots / Video
At 991px
![image](https://user-images.githubusercontent.com/60009121/103713281-d965cd80-4fb3-11eb-9900-4d1ccab81efd.png)

At 992px
![image](https://user-images.githubusercontent.com/60009121/103713141-7ffd9e80-4fb3-11eb-83dc-f8606b8602b4.png)

## Expected behavior
Expected behavior is to be able to see everything in the menu no matter the media query I'm currently in.

**Comment by SteveRyan-ASU** [comment]
This was an issue first reported in the Unity project that was fixed in a subsequent release of the CSS and recommended markup for that component. 

Here's the PR for project unity (for those that have access): https://github.com/ASU/asu-unity-stack/pull/96

> The fix was a recommended change in the markup of the menu to include a different utility class around the tag for that piece of text.

Find this: <span class="d-lg-none">Home</span>
Replace it with: <span class="d-xl-none">Home</span>
