### ISSUE TITLE
ACF Block: Icon Button

### ISSUE THREAD

**Issue by wmcconnell** [asu-ke-web-services/UDS-WordPress-Theme#93]
We need to implement a UDS Icon Button, which is a circular button with just an icon, as seen in the XD here:

[https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/76085c5e-6111-4056-afce-d2948d71a00c/](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/76085c5e-6111-4056-afce-d2948d71a00c/)

We may need to discuss the possibility of this button being configurable so that it can act as the following UDS items:

- close button (small, circular with an 'x' icon)
- previous/next button

**Comment by zainabD** [comment]
I don't see where can we use these icon's buttons?

**Comment by zainabD** [comment]
There won't be any real use of this feature as a separate block.
