### ISSUE TITLE
ACF Block: Testimonials (static)

### ISSUE THREAD

**Issue by wmcconnell** [asu-ke-web-services/UDS-WordPress-Theme#97]
We need to create a Testimonial block that implements (most) of what is [shown on the XD](https://xd.adobe.com/view/56f6cb78-9af5-4b12-b4ce-ef319f71113f-03a5/screen/c7df5234-e805-4a9e-953b-aa31a0e0391f/). We are looking for:

- Option 1 (with no sliders, only the static version)
- Option 2

There is some confusion, as the [Storybook entry for testimonials](https://unity.web.asu.edu/@asu-design-system/bootstrap4-theme/?path=/story/components-testimonials--testimonials-option-1) seems to have a different idea of what each style is named. We can meet on this once someone is assigned to this block.

**Comment by zainabD** [comment]
This was done in the blockquote block [Blockquote - New markup, new SASS #123]

**Comment by zainabD** [comment]
Confirmed with Walt that we can close this for now.
